### ISSUE TITLE
Deprecation warning when using Copy-AzureWebAppSqlDatabase (INFRA-129)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Infrastructure-Scripts#11]
When running `Copy-AzureWebAppSqlDatabase` there's a deprecation warning coming from the `Set-AzSqlDatabase` cmdlet (in a GitHub Actions workflow) I get the below warning:

```
WARNING: Upcoming breaking changes in the cmdlet 'Set-AzSqlDatabase' :

- The output type 'Microsoft.Azure.Commands.Sql.Database.Model.AzureSqlDatabaseModel' is changing
- The following properties in the output type are being deprecated : 'BackupStorageRedundancy'
- The following properties are being added to the output type : 'CurrentBackupStorageRedundancy' 'RequestedBackupStorageRedundancy'
- The change is expected to take effect from the version : '3.0.0'
```

[Jira issue](https://lombiq.atlassian.net/browse/INFRA-129)

**Comment by BenedekFarkas** [comment]
AFAIR it's not actionable for us as we're not using those properties.

**Comment by Piedone** [comment]
Great then. I suppose these will also go away once we (can) update the cmdlet.

**Comment by BenedekFarkas** [comment]
It's up to the GHA runner team to update, because they pre-install Az PS, but version 3.0.0 actually refers to the Azure SDK itself that Az PS is using under the hood, so it's even further removed from us.

**Comment by Piedone** [comment]
Ah, I see.

**Comment by BenedekFarkas** [comment]
Checked recent runs of our workflows that use this command + did my own testing in a throw-away repository and locally. I have version 4.4.0 of Az.Sql installed on my machine and it still shows the warning, but the latest one (4.10.0) that we install on the runners doesn't.

**Comment by Piedone** [comment]
Ah, nice!
